// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv523nHVccwBmKW6npHAmqx6YKIEGaFOc',
    appId: '1:682209836694:web:30c6d6cdbbf62a33bf0cb7',
    messagingSenderId: '682209836694',
    projectId: 'ignite-2b785',
    authDomain: 'ignite-2b785.firebaseapp.com',
    storageBucket: 'ignite-2b785.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9pSS4E2WU4rQa2qCCLWBvAywwknl8MoM',
    appId: '1:682209836694:android:c04f276cd2500f98bf0cb7',
    messagingSenderId: '682209836694',
    projectId: 'ignite-2b785',
    storageBucket: 'ignite-2b785.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPfkLH62HfY7b8USdTU5Tw8jmfda93OX4',
    appId: '1:682209836694:ios:5099fccaf44506ffbf0cb7',
    messagingSenderId: '682209836694',
    projectId: 'ignite-2b785',
    storageBucket: 'ignite-2b785.appspot.com',
    iosClientId: '682209836694-c6mt83ut6fmnv42dj7lmhh0foo1k01sv.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleIgniteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPfkLH62HfY7b8USdTU5Tw8jmfda93OX4',
    appId: '1:682209836694:ios:5099fccaf44506ffbf0cb7',
    messagingSenderId: '682209836694',
    projectId: 'ignite-2b785',
    storageBucket: 'ignite-2b785.appspot.com',
    iosClientId: '682209836694-c6mt83ut6fmnv42dj7lmhh0foo1k01sv.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleIgniteApp',
  );
}
